<?php
/**
 * Created by PhpStorm.
 * User: asmild
 * Date: 02.08.18
 * Time: 10:32
 */

namespace common\models\radius;
use yii\data\ActiveDataProvider;

class AccountingBlacklist extends \yii\db\ActiveRecord
{
    public static function tableName()
    {
        return 'accounts_blacklist'; // TODO: Change the autogenerated stub
    }


    public function attributeLabels()
    {
        return [
            'login' => 'Логин',
            'mac_address' => 'MAC адрес',
//            'ipv4' => 'IP адрес',
//            'nas' => 'NAS',
//            'ipv6' => 'IPv6 префикс',
//            'status' => 'Статус',
            'begin' => 'От',
//            'end' => 'До',
        ];
    }

    public function rules()
    {

        return [

            [['login','mac_address'],'trim'],
//            ['ipv4','ip','ipv4'=>true,'subnet'=> null, 'expandIPv6'=> false,"message"=>"Неверный IP адрес!"],
            ['mac_address','validateMacAddr','skipOnEmpty'=> true,'skipOnError'=>true],
//            [['begin','end'],'required'],
//            [['login','macaddr','ipv4','ipv6'],function($attribute, $params, $validator){
//                if(empty($this->login) && empty($this->macaddr) && empty($this->ipv4) && empty($this->ipv6)) {
//                    $this->addError($attribute,"Заполните хотя бы одно из полей");
//                }
//            },'skipOnEmpty'=> false,'skipOnError'=>false],
        ];
    }

    public function validateMacAddr($attribute, $params){
        if(!filter_var($this->$attribute,FILTER_VALIDATE_MAC)){
            $this->addError($attribute, "Неверный MAC адрес!");
        }
    }


    public function saveItem($params){
        $model = new AccountingBlacklist();
        $model->login = $params['login'];
        $model->mac_address = $params['mac_address'];
        $model->banned_at = time();
        return $model->save();
    }

    public function deleteItem($id){
        $model = AccountingBlacklist::findOne($id);
        return $model->delete();
    }

    public function search($params){
        $query = AccountingBlacklist::find()
            ->asArray();
//                ->where(['login'=>$post['RadiusArch']['login']])
//                ->orWhere(['mac_addr'=>$post['RadiusArch']['macaddr']])
//                ->orWhere(['ipv4_addr'=>$post['RadiusArch']['ipv4']])
//            ->where(['between','started_at',$begin,$end]);
//                ->all();


//        if($login!=''){
//            $query->andWhere(['login'=>$login]);
//        }
//        if($macaddr!=''){
//            $query->andWhere(['mac_addr'=>$macaddr]);
//        }
//        if($ipv4!=''){
//            $query->andWhere(['ipv4_addr'=>$ipv4]);
//        }
//        if($ipv6!=''){
//            $query->andWhere(['ipv6_prefix'=>$ipv6]);
//        }


        $dataProvider = new ActiveDataProvider([
            'query'=>$query,
            'pagination'=>[
                'pageSize' => 10,
                'pageSizeParam'=>false,
                'forcePageParam' => false
            ]
        ]);

        if (!($this->load($params) && $this->validate())) {
            return $dataProvider;
        }

        // adjust the query by adding the filters
        $query->andFilterWhere(['login' => $this->login]);
        $query->andFilterWhere(['mac_address' => $this->mac_address]);
        $query->andFilterWhere(['>=', 'banned_at', $this->banned_at]);//->orFilterWhere(['>=', 'stopped_at', $this->begin]);
//        $query->andFilterWhere(['<=', 'started_at', $this->end]);//->orFilterWhere(['<=', 'stopped_at', $this->end]);
        return $dataProvider;
    }

}